spring:
  application:
    name: e-learning
  datasource:
    url: jdbc:postgresql://localhost:5432/e-learning
    username: postgres
    password: donald
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true
server:
  port: 9888
